### ISSUE TITLE
Tydelig deling av "kunngjøringer"

### ISSUE THREAD

**Issue by gammalost** [KaHole/bbes#2]
Mulig å få hvert item i **Kunngjøringer** markert med feks en bullet elns? Tydelig dele de opp.

![screenshot-2017-11-17 els hjem blackboard learn](https://user-images.githubusercontent.com/11397871/32949218-53b381e8-cba2-11e7-96d8-9c8440d34b7c.png)

Bullet eller bindestrek forran TX1 og PS6

**Comment by kahole** [comment]
Merget fiks for dette -> kommer i neste update, før-premiere under:

<img width="692" alt="screen shot 2017-11-20 at 23 32 24" src="https://user-images.githubusercontent.com/9072087/33044937-3347e4fc-ce4b-11e7-9dc6-e1002086ae74.png">
