### ISSUE TITLE
Feil i emneliste når man har flere roller

### ISSUE THREAD

**Issue by svtm** [KaHole/bbes#3]
Når man har noen fag man er læringsassistent i, og noen man er student i, vises ikke studentemnene. Screenshots viser dashboardet mitt med og uten bbes
![screenshot from 2017-11-20 09-27-03](https://user-images.githubusercontent.com/9281024/33008950-680070f4-cdd5-11e7-8646-9942c2beeb8a.png)
![screenshot from 2017-11-20 09-27-17](https://user-images.githubusercontent.com/9281024/33008951-681cf300-cdd5-11e7-8282-b0918e892b18.png)

**Comment by kahole** [comment]
Se der ja. Koder i blinde når jeg selv ikke har noen emner der jeg er assistent, men har gjort et forsøk. Kan du klone/laste ned issue3 branchen og installere den gjennom "about:debugging", og se om emnene dukker opp? 🥇

**Comment by svtm** [comment]
Se der ja, ble bra det!

![screenshot from 2017-11-20 20-52-29](https://user-images.githubusercontent.com/9281024/33038396-c6e4930c-ce34-11e7-9da1-72663b9fdbd2.png)
